sudo: required
language: python
python:
  - "3.6"
script:
  - pip install -r requirements.txt
# install Eth-Bridge-PRUserial485
  - git clone https://github.com/lnls-sirius/eth-bridge-pru-serial485.git
  - cd eth-bridge-pru-serial485/client
  - sed -i s/python-sirius/python/g setup.py
  - make install
  - cd ../../
# install mathphys
  - git clone https://github.com/lnls-fac/mathphys.git
  - cd mathphys
  - python setup.py install
  - cd ../
# install siriuspy
  - cd siriuspy
  - python setup.py test

# safelist
branches:
  only:
  - master
